### ISSUE TITLE
playtesting doesn't support unknown modded entities

### ISSUE THREAD

**Issue by microlith57** [catapillie/snowberry#5]
steps to reproduce:
- open a map with entities whose mods are installed but do not have snowberry compatibility
- verify that they do not render in snowberry
- playtest the map
- verify that they do not render or have behaviour ingame

i would expect that playtesting a map would behave the same as loading it, but this is not the case.

**Comment by l-Luna** [comment]
This is partially resolved by work on the lönn support branch, but still requires work for entities without supported lönn plugins.

**Comment by microlith57** [comment]
i don't understand how not having a lönn plugin would prevent an entity from appearing when *playtesting* - surely the actual entity code itself would be enough?
generally i'd expect playtesting a map to simply load it in celeste, which wouldn't know about snowberry/lönn plugins.

**Comment by l-Luna** [comment]
When a map is opened in playtest mode, or saves to a file, Snowberry generates a new MapData object from which rooms and entities are loaded - anything that isn't saved by Snowberry won't exist, currently including entities that don't have their own plugin (since they aren't loaded by Snowberry yet otherwise).

**Comment by microlith57** [comment]
that makes sense, but it would probably be good to have a fallback plugin to store these entities to avoid this

**Comment by l-Luna** [comment]
yeah that's planned, a lot of the lua support work can be reused there too

**Comment by microlith57** [comment]
neat

**Comment by l-Luna** [comment]
hasn't been fixed _yet_

**Comment by microlith57** [comment]
oh ok
