### ISSUE TITLE
various issues i found when testing from the zip file

### ISSUE THREAD

**Issue by microlith57** [catapillie/snowberry#7]
- pressing G to render styleground previews did nothing
- the room tool didn't allow me to create rooms (there were no such buttons) on a map loaded from a folder
- mouse cursor persisted into gameplay in some cases (i will test further at some point)

more soon, perhaps

**Comment by catapillie** [comment]
the second .zip i posted in celestecord doesn't have the notes and styleground toggle controls; i hadn't pushed those, they were just for that build
